#
# Copyright (c) 2019-2020 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

image: Visual Studio 2019
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
matrix:
  fast_finish: true

build_script:
  - cp ci\ca-cert.pem C:\
  - cp ci\server-cert.pem C:\
  - cp ci\server-key.pem C:\
  - cp ci\windows-ci.cnf C:\
  - 'echo !include C:\\windows-ci.cnf >> "C:\Program Files\MySQL\MySQL Server 5.7\my.ini"'
  - net stop MySQL57 && net start MySQL57
  - set PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\Libraries\boost_1_73_0\lib64-msvc-14.2;C:\Libraries\boost_1_73_0\lib32-msvc-14.2;%PATH%
  - mysqladmin --user=root password -pPassword12! ""
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
  - mkdir build
  - cd build
  - cmake -G Ninja -DBOOST_ROOT=C:\Libraries\boost_1_73_0 -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl ..
  - cmake --build . -j

test_script:
  - ctest --output-on-failure

services:
  - mysql