#
# Copyright (c) 2019-2020 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

__linux_defaults: &__linux_defaults
  os: linux
  dist: bionic
  sudo: true
  addons:
    apt:
      update: true
      packages:
        - valgrind
        - lcov
        - ninja-build
  services:
    - docker
    
__osx_defaults: &__osx_defaults
  os: osx
  osx_image: xcode11.3
  sudo: true
  compiler: clang
  addons:
    homebrew:
      packages:
        - ninja
        - mysql
        - lcov
    
language: cpp
script: bash -e -x tools/build_unix.sh

matrix:
  include:
    # Other database version builds (CMake Linux)
    - name: cmake_linux_clang_debug_mysql5
      <<: *__linux_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql:5
        - USE_VALGRIND=1
        - USE_COVERAGE=1
    - name: cmake_linux_clang_debug_mariadb
      <<: *__linux_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mariadb:10.3
        - USE_VALGRIND=1
        - USE_COVERAGE=1

    # B2 builds
    - name: b2_linux_clang_mysql8
      <<: *__linux_defaults
      env:
        - DATABASE=mysql:8
        - B2_CXXSTD=17
        - B2_TOOLSET=clang
        - B2_VARIANT=debug,release
    - name: b2_osx_clang_mysql8
      <<: *__osx_defaults
      env:
        - DATABASE=mysql:8
        - B2_CXXSTD=17
        - B2_TOOLSET=clang
        - B2_VARIANT=debug,release
    # Linux CMake builds
    - name: cmake_linux_clang10_debug_mysql8
      <<: *__linux_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql:8
        - USE_COVERAGE=1
        - CMAKE_CXX_FLAGS="-stdlib=libc++ -DBOOST_ASIO_DISABLE_CONCEPTS"
        - CMAKE_OPTIONS="-DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 -DCMAKE_CXX_STANDARD=20"
      install:
        - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        - sudo apt install clang-10 libc++-10-dev libc++abi-10-dev
    - name: cmake_linux_gcc_debug_mysql8
      <<: *__linux_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql:8
        - USE_VALGRIND=1
        - USE_COVERAGE=1
    - name: cmake_linux_gcc_release_mysql8
      <<: *__linux_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mysql:8
    - name: cmake_linux_clang_debug_mysql8
      <<: *__linux_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql:8
        - USE_VALGRIND=1
        - USE_COVERAGE=1
    - name: cmake_linux_clang_release_mysql8
      <<: *__linux_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mysql:8
    
    # CMake OSX builds
    - name: cmake_osx_clang_debug_mysql8
      <<: *__osx_defaults
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql:8
        - USE_COVERAGE=1
    - name: cmake_osx_clang_release_mysql8
      <<: *__osx_defaults
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mysql:8
        
        