#
# Copyright (c) 2019-2020 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

__linux_addons_defaults: &__linux_addons_defaults
  apt:
    update: true
    packages:
      - python3
      - valgrind
      - lcov
      - ninja-build

__linux_defaults: &__linux_defaults
  os: linux
  dist: bionic
  sudo: true
  addons:
    <<: *__linux_addons_defaults
  script:
    - bash -e -x tools/build_unix.sh
    
__linux_mysql_defaults: &__linux_mysql_defaults
  <<: *__linux_defaults
  services:
    - mysql
    
__linux_mariadb_defaults: &__linux_mariadb_defaults
  <<: *__linux_defaults
  addons:
    <<: *__linux_addons_defaults
    mariadb: '10.3'

__osx_defaults: &__osx_defaults
  os: osx
  osx_image: xcode11.3
  sudo: true
  compiler: clang
  script:
    - bash -e -x tools/build_unix.sh
    
language: cpp

matrix:
  include:
    - name: linux_clang10_x64_debug_mysql
      <<: *__linux_mysql_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql
        - USE_COVERAGE=1
        - CMAKE_CXX_FLAGS="-stdlib=libc++ -DBOOST_ASIO_DISABLE_CONCEPTS"
        - CMAKE_OPTIONS="-DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 -DCMAKE_CXX_STANDARD=20"
      install:
        - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        - sudo apt install clang-10 libc++-10-dev libc++abi-10-dev
    - name: linux_gcc_x64_debug_mysql
      <<: *__linux_mysql_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql
        - USE_VALGRIND=1
        - USE_COVERAGE=1
    - name: linux_gcc_x64_release_mysql
      <<: *__linux_mysql_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mysql
    - name: linux_clang_x64_debug_mysql
      <<: *__linux_mysql_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql
        - USE_VALGRIND=1
        - USE_COVERAGE=1
    - name: linux_clang_x64_release_mysql
      <<: *__linux_mysql_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mysql
    - name: linux_gcc_x64_debug_mariadb
      <<: *__linux_mariadb_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mariadb
        - USE_VALGRIND=1
        - USE_COVERAGE=1
    - name: linux_gcc_x64_release_mariadb
      <<: *__linux_mariadb_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mariadb
    - name: linux_clang_x64_debug_mariadb
      <<: *__linux_mariadb_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mariadb
        - USE_VALGRIND=1
        - USE_COVERAGE=1
    - name: linux_clang_x64_release_mariadb
      <<: *__linux_mariadb_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mariadb
    - name: osx_clang_x64_debug_mysql
      <<: *__osx_defaults
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql
        - USE_COVERAGE=1
        - HAS_SHA256=1
    - name: osx_clang_x64_release_mysql
      <<: *__osx_defaults
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mysql
        - HAS_SHA256=1
    - name: osx_clang_x64_debug_mariadb
      <<: *__osx_defaults
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mariadb
        - USE_COVERAGE=1
    - name: osx_clang_x64_release_mariadb
      <<: *__osx_defaults
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mariadb
